version: '3.8'

services:
  aliexpress-ai-hunter:
    build: https://github.com/ausamnco/aliexpress-ai-hunter.git#main
    image: ghcr.io/ausamnco/aliexpress-ai-hunter:latest
    container_name: aliexpress-ai-hunter
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./aliexpress-ai-hunter/data:/data
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PATH=/data/searches.db
    shm_size: '2gb'
